#if !canImport(ObjectiveC)
import XCTest

extension CollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionTests = [
        ("testElementValidation", testElementValidation),
        ("testLengthValidation", testLengthValidation),
    ]
}

extension ComparableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComparableTests = [
        ("testGreaterThan", testGreaterThan),
        ("testLessThan", testLessThan),
        ("testNumberThousand", testNumberThousand),
    ]
}

extension FailableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FailableTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
        ("testInit", testInit),
        ("testKeyPathSubscript", testKeyPathSubscript),
        ("testSet", testSet),
    ]
}

extension OptionalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionalTests = [
        ("testNotNil", testNotNil),
        ("testNotNilValidate", testNotNilValidate),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testUSPhoneNumber", testUSPhoneNumber),
    ]
}

extension ValidationErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidationErrorTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
        ("testInit", testInit),
    ]
}

extension ValidationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidationTests = [
        ("testDefaultImplementations", testDefaultImplementations),
        ("testSafeSubvalidations", testSafeSubvalidations),
        ("testType", testType),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CollectionTests.__allTests__CollectionTests),
        testCase(ComparableTests.__allTests__ComparableTests),
        testCase(FailableTests.__allTests__FailableTests),
        testCase(OptionalTests.__allTests__OptionalTests),
        testCase(StringTests.__allTests__StringTests),
        testCase(ValidationErrorTests.__allTests__ValidationErrorTests),
        testCase(ValidationTests.__allTests__ValidationTests),
    ]
}
#endif
